// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Kentico.Kontent.Statiq.Lumen.Models
{
    public partial class Article
    {
        public const string Codename = "article";
        public const string AuthorCodename = "author";
        public const string CategoryCodename = "category";
        public const string ContentCodename = "content";
        public const string DescriptionCodename = "description";
        public const string OgDescriptionCodename = "og__description";
        public const string OgImageCodename = "og__image";
        public const string OgTitleCodename = "og__title";
        public const string PublishDateCodename = "publish_date";
        public const string SlugCodename = "slug";
        public const string TagsCodename = "tags";
        public const string TitleCodename = "title";
        public const string TwitterCardCodename = "twitter__card";
        public const string TwitterCreatorCodename = "twitter__creator";
        public const string TwitterImageCodename = "twitter__image";
        public const string TwitterSiteCodename = "twitter__site";

        public IEnumerable<object> Author { get; set; }
        public IEnumerable<object> Category { get; set; }
        public string Content { get; set; }
        public string Description { get; set; }
        public string OgDescription { get; set; }
        public IEnumerable<IAsset> OgImage { get; set; }
        public string OgTitle { get; set; }
        public DateTime? PublishDate { get; set; }
        public string Slug { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public IEnumerable<object> Tags { get; set; }
        public string Title { get; set; }
        public IEnumerable<IMultipleChoiceOption> TwitterCard { get; set; }
        public string TwitterCreator { get; set; }
        public IEnumerable<IAsset> TwitterImage { get; set; }
        public string TwitterSite { get; set; }
    }
}