// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Kentico.Kontent.Statiq.Lumen.Models
{
    public partial class Homepage
    {
        public const string Codename = "homepage";
        public const string ContentCodename = "content";
        public const string SubpagesCodename = "subpages";
        public const string TitleCodename = "title";

        public IEnumerable<object> Content { get; set; }
        public IEnumerable<object> Subpages { get; set; }
        public IContentItemSystemAttributes System { get; set; }
        public string Title { get; set; }
    }
}