name: .NET Core

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: content-changed
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Publish
      run: dotnet publish PetrSvihlik.Com.csproj --configuration Release --no-build -o ./tools
    - name: "Artifact : generator"
      uses: actions/upload-artifact@v4
      with:
        name: "Generator"
        path: ./tools
    - name: Publish
      run: dotnet run --configuration Release  
      env:
        LinkRoot: ${{ secrets.LINKROOT }} # Fix subfolder links https://statiq.dev/framework/configuration/settings
        Host:  ${{ secrets.HOST }} # Make links absolute (for feeds, OG...)
    - name: "Artifact : site"
      uses: actions/upload-artifact@v4
      with:
        name: "Site"
        path: ./output     
    - name: Deploy 🚀
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@v4.7.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        folder: output
        clean: true # Automatically remove deleted files from the deploy branch
